environment:
  nuget_version: '0.12.0-alpha1'
  nuget_prerelease: true
  assembly_version: '0.12.0.0'

image: Visual Studio 2017

deploy:
  - provider: GitHub
    description: |
      * add lines here

    on:
      appveyor_repo_tag: true
    prerelease: $(nuget_prerelease)

    release: v$(nuget_version)
    auth_token:
      secure: VrF5TrpBRN0ims9nJC1LG32O6ga5hsRuGNSufEbatAiIWZ1z68iiCYKZtqnAaT9y

  - provider: NuGet
    api_key:
      secure: R+qirYPrTX9IzJHpRLL6KAV1Lo+vlAnInf6ShiIB2rAGIP28ceJxRAh1jirHE/uD
    on:
      appveyor_repo_tag: true

pull_requests:
  do_not_increment_build_number: true

clone_depth: 5

version: '$(nuget_version)+{build}'
configuration: Release

# build_script:
# - cmd: >-
#     powershell -f build.ps1 -CodeDirectory "Source" -TestsDirectory "Source" -PackageOutputDirectory "Build" -Package "Machine.Specifications" -Version "%NUGET_VERSION%" -Configuration "%CONFIGURATION%"

artifacts:
- path: Build\*.nupkg

test: off

